FORMAT: 1A

# Equation solver
This API will be used in a system for solving equations

# Equation solver Root [/]
Equation solver Home page

## Retrieve Home Page [GET]
+ Response 200

# Group equations
A group for the commited equations

## Equation [/equations/{id}]
An equation has five parameters
    - id
    - user
    - created_at
    - equation
    - solution
+ Parameters
    + id (string)

+ Model

### Retrieve a single equation [GET]
+ Response 200

    [Equation][]