FORMAT: 1A

# Equation solver
This API will be used in a system for solving equations

# Group equations
A group for the commited equations

## Equations [/equations]
An equation has five parameters
    - id
    - user
    - created_at
    - equation
    - solution
### List all equations [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "user": "anton",
            "created_at": "21:00:00 28.02.2015",
            "equation": "x + 1 = 0",
            "solution": -1
        }, {
            "id": 2,
            "user": "kiril",
            "created_at": "06:53:24 10.03.2015",
            "equation": "x - 2 = 0",
            "solution": 2
        }]

### Add an equation [POST]
+ Request (application/json)

        {
            "user": "anton",
            "equation": "x + 1 = 0"
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "user": "anton",
            "created_at": "21:00:00 28.02.2015",
            "equation": "x + 1 = 0"
        }

## Equation [/equations/{id}]
A single equation

+ Parameters
    + id (required, number)

### Get equation details [GET]
+ Response 200 (application/json)

    + Body
    
            {
                "id": 1,
                "user": "anton",
                "created_at": "21:00:00 28.02.2015",
                "equation": "x + 1 = 0",
                "solution": -1
            }

### Edit an equation [PUT]
+ Request (application/json)

    + Body

            {
                "user": "anton",
                "equation": "x + 2 = 0"
            }

+ Response 200 (application/json)

    + Body
    
            {
                "id": 1,
                "user": "anton",
                "equation": "x + 2 = 0"
            }

### Remove an equation [DELETE]
+ Response 204

# Group function
A group for the commited functions

## Functions [/functions]
A function has five parameters
    - id
    - user
    - created_at
    - function
    - graphics
### Get all functions [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "user": "anton",
            "created_at": "14:05:43 13.02.2015",
            "function": "x + y",
            "graphics": "1.png"
        }, {
            "id": 2,
            "user": "kiril",
            "created_at": "10:33:57 13.03.2015",
            "function": "x + 7",
            "graphics": "2.png"
        }]

### Add a function [POST]
+ Request (application/json)

        {
            "user": "anton",
            "function": "x + y"
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "user": "anton",
            "created_at": "14:05:43 13.02.2015",
            "function": "x + y"
        }

## Function [/functions/{id}]
A single function

+ Parameters
    + id (required, number)

### Get function details [GET]
+ Response 200 (application/json)

    + Body
    
            {
                "id": 1,
                "user": "anton",
                "created_at": "14:05:43 13.02.2015",
                "function": "x + y",
                "graphics": "1.png"
            }

### Edit a function [PUT]
+ Request (application/json)

    + Body
    
            {
                "user": "anton",
                "function": "x + z"
            }

+ Response 200 (application/json)

    + Body
    
            {
                "id": 1,
                "user": "anton",
                "function": "x + z"
            }

### Remove a function [DELETE]
+ Response 204